---
title: "R for Beginners"
image: 
links:
  # - label: LinkedIn
  #   url: "https://linkedin.com/"
  # - label: Twitter
  #   url: "https://twitter.com/"
  - label: '<i class="fab fa-github"></i>GitHub'
    url: "https://github.com/jennysloane/r4beginners"
  - label: '<i class="fas fa-envelop"></i>Contact Us'
    url: "mailto:jfsloane92@gmail.com"
output:
  postcards::trestles
site: distill::distill_website
---
 
<!-- github help page to set up custom domain (Configuring an apex domain): https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain -->

# Welcome

Are you interested in learning how to code in R, but have no idea where to start? If this is you... you've come to the right place!

The goal of this website is to make learning R fun and easy! Although many people find the idea of learning how to code to be daunting and overwhelming, it doesn't need to be. With the right resources and tools, coding can be enjoyable and incredibly rewarding! 

On this website, you will find hours of tutorials to help you begin your R coding journey. We will cover everything from introducing you to RStudio, to writing your first R Markdown script, to learning about dataframes and different types of variables. 

$\checkmark$ [Getting Started](https://jennysloane.netlify.app/): We highly recommend you start your journey by going through the tutorials in the Getting Started section, especially if you are new to programming. <br>
$\checkmark$ [Workshops](https://jennysloane.netlify.app/): The workshops are designed for beginners and we make sure to cover all of the basics and fundamentals. <br>
$\checkmark$ [Websites](https://jennysloane.netlify.app/): Do you want to apply your new R skills and build your own website? Check out the tutorials to help you build a website using the `distill` or `blogdown` package.


<div class="license">
**License and Citation:** You can use, share, modify, and adapt any of the tutorials or lessons, but please include the following attribution: *R4Beginners. (May 30, 2022). Zenodo. [https://doi.org/10.5281/zenodo.6595406](https://doi.org/10.5281/zenodo.6595406)*
</div>

*Please note - this website is still being developed, so stay tuned for more lessons and tutorials!*
